// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title BaseforPhrases
 * @notice Library containing all Basefor phrases
 * @dev Used by BaseforPhrasesRegistry for gas-efficient phrase storage
 */
library BaseforPhrases {
    /**
     * @notice Get phrase by ID
     * @param phraseId The phrase ID (1-299)
     * @return The phrase string
     */
    function getPhrase(uint256 phraseId) internal pure returns (string memory) {
        if (phraseId == 1) return "{onchain home}";
        else if (phraseId == 2) return "{open world}";
        else if (phraseId == 3) return "{build here}";
        else if (phraseId == 4) return "{new culture}";
        else if (phraseId == 5) return "{pure onchain}";
        else if (phraseId == 6) return "{always open}";
        else if (phraseId == 7) return "{open access}";
        else if (phraseId == 8) return "{global value}";
        else if (phraseId == 9) return "{instant trust}";
        else if (phraseId == 10) return "{chain native}";
        else if (phraseId == 11) return "{build freely}";
        else if (phraseId == 12) return "{onchain life}";
        else if (phraseId == 13) return "{digital tribe}";
        else if (phraseId == 14) return "{collective mind}";
        else if (phraseId == 15) return "{open path}";
        else if (phraseId == 16) return "{new frontier}";
        else if (phraseId == 17) return "{chain culture}";
        else if (phraseId == 18) return "{infinite canvas}";
        else if (phraseId == 19) return "{true ownership}";
        else if (phraseId == 20) return "{seamless flow}";
        else if (phraseId == 21) return "{open doors}";
        else if (phraseId == 22) return "{visible value}";
        else if (phraseId == 23) return "{real identity}";
        else if (phraseId == 24) return "{community first}";
        else if (phraseId == 25) return "{permissionless power}";
        else if (phraseId == 26) return "{pure creation}";
        else if (phraseId == 27) return "{living network}";
        else if (phraseId == 28) return "{public commons}";
        else if (phraseId == 29) return "{shared roots}";
        else if (phraseId == 30) return "{code culture}";
        else if (phraseId == 31) return "{trust minimized}";
        else if (phraseId == 32) return "{open rails}";
        else if (phraseId == 33) return "{decentralized heart}";
        else if (phraseId == 34) return "{global state}";
        else if (phraseId == 35) return "{future now}";
        else if (phraseId == 36) return "{onchain future}";
        else if (phraseId == 37) return "{free to build}";
        else if (phraseId == 38) return "{open networks}";
        else if (phraseId == 39) return "{digital kin}";
        else if (phraseId == 40) return "{borderless tech}";
        else if (phraseId == 41) return "{value moves}";
        else if (phraseId == 42) return "{chain powered}";
        else if (phraseId == 43) return "{onchain ready}";
        else if (phraseId == 44) return "{unstoppable flow}";
        else if (phraseId == 45) return "{immutable truth}";
        else if (phraseId == 46) return "{creativity unlocked}";
        else if (phraseId == 47) return "{network growing}";
        else if (phraseId == 48) return "{chain energy}";
        else if (phraseId == 49) return "{onchain first}";
        else if (phraseId == 50) return "{infinite builders}";
        else if (phraseId == 51) return "{real coordination}";
        else if (phraseId == 52) return "{frictionless value}";
        else if (phraseId == 53) return "{shared ledger}";
        else if (phraseId == 54) return "{collective growth}";
        else if (phraseId == 55) return "{code-native world}";
        else if (phraseId == 56) return "{trustless future}";
        else if (phraseId == 57) return "{open economies}";
        else if (phraseId == 58) return "{digital sovereignty}";
        else if (phraseId == 59) return "{new beginnings}";
        else if (phraseId == 60) return "{culture evolves}";
        else if (phraseId == 61) return "{permissionless art}";
        else if (phraseId == 62) return "{pure signal}";
        else if (phraseId == 63) return "{onchain voice}";
        else if (phraseId == 64) return "{global heartbeat}";
        else if (phraseId == 65) return "{builder energy}";
        else if (phraseId == 66) return "{always onchain}";
        else if (phraseId == 67) return "{construct freely}";
        else if (phraseId == 68) return "{people-powered}";
        else if (phraseId == 69) return "{digital pulse}";
        else if (phraseId == 70) return "{network unity}";
        else if (phraseId == 71) return "{belong onchain}";
        else if (phraseId == 72) return "{identity unchained}";
        else if (phraseId == 73) return "{build together}";
        else if (phraseId == 74) return "{programmable world}";
        else if (phraseId == 75) return "{fluid value}";
        else if (phraseId == 76) return "{unbounded access}";
        else if (phraseId == 77) return "{instant belonging}";
        else if (phraseId == 78) return "{coordinated future}";
        else if (phraseId == 79) return "{open rhythm}";
        else if (phraseId == 80) return "{shared imagination}";
        else if (phraseId == 81) return "{tech spirit}";
        else if (phraseId == 82) return "{chain spirit}";
        else if (phraseId == 83) return "{open maps}";
        else if (phraseId == 84) return "{free flow}";
        else if (phraseId == 85) return "{community engine}";
        else if (phraseId == 86) return "{native onchain}";
        else if (phraseId == 87) return "{network soul}";
        else if (phraseId == 88) return "{shared purpose}";
        else if (phraseId == 89) return "{digital warmth}";
        else if (phraseId == 90) return "{collective spark}";
        else if (phraseId == 91) return "{unified build}";
        else if (phraseId == 92) return "{authenticated life}";
        else if (phraseId == 93) return "{real time}";
        else if (phraseId == 94) return "{connect freely}";
        else if (phraseId == 95) return "{own everything}";
        else if (phraseId == 96) return "{culture grows}";
        else if (phraseId == 97) return "{onchain moves}";
        else if (phraseId == 98) return "{digital presence}";
        else if (phraseId == 99) return "{shared world}";
        else if (phraseId == 100) return "{trustless rails}";
        else if (phraseId == 101) return "{creative pulse}";
        else if (phraseId == 102) return "{community-driven}";
        else if (phraseId == 103) return "{transparent value}";
        else if (phraseId == 104) return "{borderless money}";
        else if (phraseId == 105) return "{future-shaped}";
        else if (phraseId == 106) return "{code-powered}";
        else if (phraseId == 107) return "{network born}";
        else if (phraseId == 108) return "{true openness}";
        else if (phraseId == 109) return "{always inclusive}";
        else if (phraseId == 110) return "{public space}";
        else if (phraseId == 111) return "{infinite tribes}";
        else if (phraseId == 112) return "{tech frontier}";
        else if (phraseId == 113) return "{collective code}";
        else if (phraseId == 114) return "{global tribe}";
        else if (phraseId == 115) return "{connected minds}";
        else if (phraseId == 116) return "{onchain breath}";
        else if (phraseId == 117) return "{world syncing}";
        else if (phraseId == 118) return "{trustless flow}";
        else if (phraseId == 119) return "{digital kinship}";
        else if (phraseId == 120) return "{fluid identity}";
        else if (phraseId == 121) return "{chain-born}";
        else if (phraseId == 122) return "{permissionless life}";
        else if (phraseId == 123) return "{native digital}";
        else if (phraseId == 124) return "{shared state}";
        else if (phraseId == 125) return "{open rhythm}";
        else if (phraseId == 126) return "{real digital}";
        else if (phraseId == 127) return "{ecosystem rising}";
        else if (phraseId == 128) return "{pure economy}";
        else if (phraseId == 129) return "{value unlocked}";
        else if (phraseId == 130) return "{creator realm}";
        else if (phraseId == 131) return "{tech commons}";
        else if (phraseId == 132) return "{chain-native art}";
        else if (phraseId == 133) return "{network alive}";
        else if (phraseId == 134) return "{coordinated minds}";
        else if (phraseId == 135) return "{shared canvas}";
        else if (phraseId == 136) return "{collective orbit}";
        else if (phraseId == 137) return "{digital unity}";
        else if (phraseId == 138) return "{public protocol}";
        else if (phraseId == 139) return "{culture encoded}";
        else if (phraseId == 140) return "{open heartbeat}";
        else if (phraseId == 141) return "{onchain cluster}";
        else if (phraseId == 142) return "{community roots}";
        else if (phraseId == 143) return "{future-coded}";
        else if (phraseId == 144) return "{network culture}";
        else if (phraseId == 145) return "{onchain together}";
        else if (phraseId == 146) return "{shared journeys}";
        else if (phraseId == 147) return "{digital harmony}";
        else if (phraseId == 148) return "{built together}";
        else if (phraseId == 149) return "{open creation}";
        else if (phraseId == 150) return "{network rising}";
        else if (phraseId == 151) return "{open circuits}";
        else if (phraseId == 152) return "{digital commons}";
        else if (phraseId == 153) return "{chain cohesion}";
        else if (phraseId == 154) return "{collective rise}";
        else if (phraseId == 155) return "{fluid networks}";
        else if (phraseId == 156) return "{onchain unity}";
        else if (phraseId == 157) return "{motion native}";
        else if (phraseId == 158) return "{infinite state}";
        else if (phraseId == 159) return "{shared future}";
        else if (phraseId == 160) return "{open identity}";
        else if (phraseId == 161) return "{culture native}";
        else if (phraseId == 162) return "{network breath}";
        else if (phraseId == 163) return "{living protocol}";
        else if (phraseId == 164) return "{global mesh}";
        else if (phraseId == 165) return "{boundless sync}";
        else if (phraseId == 166) return "{chain alive}";
        else if (phraseId == 167) return "{digital union}";
        else if (phraseId == 168) return "{culture pulse}";
        else if (phraseId == 169) return "{infinite reach}";
        else if (phraseId == 170) return "{shared rhythm}";
        else if (phraseId == 171) return "{code tribes}";
        else if (phraseId == 172) return "{free movement}";
        else if (phraseId == 173) return "{chain harmony}";
        else if (phraseId == 174) return "{unified motion}";
        else if (phraseId == 175) return "{trust web}";
        else if (phraseId == 176) return "{digital light}";
        else if (phraseId == 177) return "{chain clarity}";
        else if (phraseId == 178) return "{creative mesh}";
        else if (phraseId == 179) return "{micro-economies}";
        else if (phraseId == 180) return "{builders unite}";
        else if (phraseId == 181) return "{value signal}";
        else if (phraseId == 182) return "{layered culture}";
        else if (phraseId == 183) return "{culture mesh}";
        else if (phraseId == 184) return "{programmable people}";
        else if (phraseId == 185) return "{shared soul}";
        else if (phraseId == 186) return "{open realm}";
        else if (phraseId == 187) return "{onchain kin}";
        else if (phraseId == 188) return "{bright network}";
        else if (phraseId == 189) return "{aligned minds}";
        else if (phraseId == 190) return "{boundless value}";
        else if (phraseId == 191) return "{protocol home}";
        else if (phraseId == 192) return "{sync together}";
        else if (phraseId == 193) return "{always building}";
        else if (phraseId == 194) return "{network glow}";
        else if (phraseId == 195) return "{creative wave}";
        else if (phraseId == 196) return "{chain warmth}";
        else if (phraseId == 197) return "{open layers}";
        else if (phraseId == 198) return "{value circles}";
        else if (phraseId == 199) return "{digital orbit}";
        else if (phraseId == 200) return "{code kinship}";
        else if (phraseId == 201) return "{global sync}";
        else if (phraseId == 202) return "{living mesh}";
        else if (phraseId == 203) return "{heartchain}";
        else if (phraseId == 204) return "{digital ether}";
        else if (phraseId == 205) return "{onchain matter}";
        else if (phraseId == 206) return "{trust fabric}";
        else if (phraseId == 207) return "{culture web}";
        else if (phraseId == 208) return "{shared air}";
        else if (phraseId == 209) return "{beyond borders}";
        else if (phraseId == 210) return "{worldchain}";
        else if (phraseId == 211) return "{open horizon}";
        else if (phraseId == 212) return "{digital horizon}";
        else if (phraseId == 213) return "{value cloud}";
        else if (phraseId == 214) return "{chain spark}";
        else if (phraseId == 215) return "{flow state}";
        else if (phraseId == 216) return "{people-powered}";
        else if (phraseId == 217) return "{network heart}";
        else if (phraseId == 218) return "{collective code}";
        else if (phraseId == 219) return "{human ledger}";
        else if (phraseId == 220) return "{value breath}";
        else if (phraseId == 221) return "{native pulse}";
        else if (phraseId == 222) return "{digital hum}";
        else if (phraseId == 223) return "{culture map}";
        else if (phraseId == 224) return "{layered unity}";
        else if (phraseId == 225) return "{network bloom}";
        else if (phraseId == 226) return "{shared origin}";
        else if (phraseId == 227) return "{chain continuum}";
        else if (phraseId == 228) return "{onchain orbit}";
        else if (phraseId == 229) return "{culture wave}";
        else if (phraseId == 230) return "{infinite node}";
        else if (phraseId == 231) return "{global relay}";
        else if (phraseId == 232) return "{creative signal}";
        else if (phraseId == 233) return "{digital drift}";
        else if (phraseId == 234) return "{chain canvas}";
        else if (phraseId == 235) return "{onchain spark}";
        else if (phraseId == 236) return "{mesh culture}";
        else if (phraseId == 237) return "{real signal}";
        else if (phraseId == 238) return "{culture chain}";
        else if (phraseId == 239) return "{cloud tribe}";
        else if (phraseId == 240) return "{culture point}";
        else if (phraseId == 241) return "{network soil}";
        else if (phraseId == 242) return "{digital seed}";
        else if (phraseId == 243) return "{interconnected}";
        else if (phraseId == 244) return "{value web}";
        else if (phraseId == 245) return "{shared code}";
        else if (phraseId == 246) return "{community mesh}";
        else if (phraseId == 247) return "{open pulse}";
        else if (phraseId == 248) return "{chain dwell}";
        else if (phraseId == 249) return "{woven value}";
        else if (phraseId == 250) return "{digital nest}";
        else if (phraseId == 251) return "{global weave}";
        else if (phraseId == 252) return "{open weave}";
        else if (phraseId == 253) return "{world mesh}";
        else if (phraseId == 254) return "{shared link}";
        else if (phraseId == 255) return "{trust mesh}";
        else if (phraseId == 256) return "{chain ripple}";
        else if (phraseId == 257) return "{value ripple}";
        else if (phraseId == 258) return "{creative link}";
        else if (phraseId == 259) return "{network soul}";
        else if (phraseId == 260) return "{onchain drift}";
        else if (phraseId == 261) return "{culture spark}";
        else if (phraseId == 262) return "{programmable life}";
        else if (phraseId == 263) return "{digital habitat}";
        else if (phraseId == 264) return "{chain habitat}";
        else if (phraseId == 265) return "{mesh unity}";
        else if (phraseId == 266) return "{flow culture}";
        else if (phraseId == 267) return "{trust layer}";
        else if (phraseId == 268) return "{onchain bloom}";
        else if (phraseId == 269) return "{value field}";
        else if (phraseId == 270) return "{digital quiet}";
        else if (phraseId == 271) return "{chain whisper}";
        else if (phraseId == 272) return "{open whisper}";
        else if (phraseId == 273) return "{soft network}";
        else if (phraseId == 274) return "{onchain calm}";
        else if (phraseId == 275) return "{layered trust}";
        else if (phraseId == 276) return "{story chain}";
        else if (phraseId == 277) return "{chain stories}";
        else if (phraseId == 278) return "{digital tide}";
        else if (phraseId == 279) return "{shared tide}";
        else if (phraseId == 280) return "{human-aligned}";
        else if (phraseId == 281) return "{people-aligned}";
        else if (phraseId == 282) return "{collective flow}";
        else if (phraseId == 283) return "{global pulse}";
        else if (phraseId == 284) return "{shared pulse}";
        else if (phraseId == 285) return "{network echo}";
        else if (phraseId == 286) return "{culture echo}";
        else if (phraseId == 287) return "{chain echo}";
        else if (phraseId == 288) return "{signal rise}";
        else if (phraseId == 289) return "{real culture}";
        else if (phraseId == 290) return "{infinite flow}";
        else if (phraseId == 291) return "{open elements}";
        else if (phraseId == 292) return "{chain elements}";
        else if (phraseId == 293) return "{sync culture}";
        else if (phraseId == 294) return "{digital winds}";
        else if (phraseId == 295) return "{onchain breath}";
        else if (phraseId == 296) return "{unified trust}";
        else if (phraseId == 297) return "{chain together}";
        else if (phraseId == 298) return "{culture alive}";
        else if (phraseId == 299) return "{infinite together}";
        else return "}";
    }
}
