// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title WhatIsBaseForPhrases
 * @notice Library containing all WhatIsBaseFor phrases
 * @dev Used by WhatIsBaseForPhrasesRegistry for gas-efficient phrase storage
 */
library WhatIsBaseForPhrases {
    /**
     * @notice Get phrase by ID
     * @param phraseId The phrase ID (1-299)
     * @return The phrase string
     */
    function getPhrase(uint256 phraseId) internal pure returns (string memory) {
        if (phraseId == 1) return "[ONCHAIN HOME]";
        else if (phraseId == 2) return "[OPEN WORLD]";
        else if (phraseId == 3) return "[BUILD HERE]";
        else if (phraseId == 4) return "[NEW CULTURE]";
        else if (phraseId == 5) return "[PURE ONCHAIN]";
        else if (phraseId == 6) return "[ALWAYS OPEN]";
        else if (phraseId == 7) return "[OPEN ACCESS]";
        else if (phraseId == 8) return "[GLOBAL VALUE]";
        else if (phraseId == 9) return "[INSTANT TRUST]";
        else if (phraseId == 10) return "[CHAIN NATIVE]";
        else if (phraseId == 11) return "[BUILD FREELY]";
        else if (phraseId == 12) return "[ONCHAIN LIFE]";
        else if (phraseId == 13) return "[DIGITAL TRIBE]";
        else if (phraseId == 14) return "[SHARED MIND]";
        else if (phraseId == 15) return "[OPEN PATH]";
        else if (phraseId == 16) return "[NEW FRONTIER]";
        else if (phraseId == 17) return "[CHAIN CULTURE]";
        else if (phraseId == 18) return "[OPEN CANVAS]";
        else if (phraseId == 19) return "[OWN IT ALL]";
        else if (phraseId == 20) return "[SEAMLESS FLOW]";
        else if (phraseId == 21) return "[OPEN DOORS]";
        else if (phraseId == 22) return "[VISIBLE VALUE]";
        else if (phraseId == 23) return "[REAL IDENTITY]";
        else if (phraseId == 24) return "[PEOPLE FIRST]";
        else if (phraseId == 25) return "[FREE POWER]";
        else if (phraseId == 26) return "[PURE CREATION]";
        else if (phraseId == 27) return "[LIVE NETWORK]";
        else if (phraseId == 28) return "[OPEN COMMONS]";
        else if (phraseId == 29) return "[SHARED ROOTS]";
        else if (phraseId == 30) return "[CODE CULTURE]";
        else if (phraseId == 31) return "[LESS TRUST]";
        else if (phraseId == 32) return "[OPEN RAILS]";
        else if (phraseId == 33) return "[OPEN HEART]";
        else if (phraseId == 34) return "[GLOBAL STATE]";
        else if (phraseId == 35) return "[FUTURE NOW]";
        else if (phraseId == 36) return "[ONCHAIN FUTURE]";
        else if (phraseId == 37) return "[FREE TO BUILD]";
        else if (phraseId == 38) return "[OPEN NETWORKS]";
        else if (phraseId == 39) return "[DIGITAL KIN]";
        else if (phraseId == 40) return "[NO BORDERS]";
        else if (phraseId == 41) return "[VALUE MOVES]";
        else if (phraseId == 42) return "[CHAIN POWERED]";
        else if (phraseId == 43) return "[ONCHAIN READY]";
        else if (phraseId == 44) return "[ENDLESS FLOW]";
        else if (phraseId == 45) return "[FIXED TRUTH]";
        else if (phraseId == 46) return "[CREATE FREE]";
        else if (phraseId == 47) return "[NET GROWING]";
        else if (phraseId == 48) return "[CHAIN ENERGY]";
        else if (phraseId == 49) return "[ONCHAIN FIRST]";
        else if (phraseId == 50) return "[ALL BUILDERS]";
        else if (phraseId == 51) return "[REAL SYNC]";
        else if (phraseId == 52) return "[SMOOTH VALUE]";
        else if (phraseId == 53) return "[SHARED LEDGER]";
        else if (phraseId == 54) return "[SHARED GROWTH]";
        else if (phraseId == 55) return "[CODE WORLD]";
        else if (phraseId == 56) return "[TRUST-FREE]";
        else if (phraseId == 57) return "[OPEN ECONOMY]";
        else if (phraseId == 58) return "[DIGITAL FREE]";
        else if (phraseId == 59) return "[NEW START]";
        else if (phraseId == 60) return "[CULTURE GROWS]";
        else if (phraseId == 61) return "[FREE ART]";
        else if (phraseId == 62) return "[PURE SIGNAL]";
        else if (phraseId == 63) return "[ONCHAIN VOICE]";
        else if (phraseId == 64) return "[WORLD PULSE]";
        else if (phraseId == 65) return "[BUILD VIBE]";
        else if (phraseId == 66) return "[ALL ONCHAIN]";
        else if (phraseId == 67) return "[BUILD FREELY]";
        else if (phraseId == 68) return "[PEOPLE POWER]";
        else if (phraseId == 69) return "[DIGITAL PULSE]";
        else if (phraseId == 70) return "[NETWORK UNITY]";
        else if (phraseId == 71) return "[CHAIN BELONG]";
        else if (phraseId == 72) return "[FREE IDENTITY]";
        else if (phraseId == 73) return "[CO-BUILD]";
        else if (phraseId == 74) return "[CODE REALITY]";
        else if (phraseId == 75) return "[FLUID VALUE]";
        else if (phraseId == 76) return "[FULL ACCESS]";
        else if (phraseId == 77) return "[BELONG NOW]";
        else if (phraseId == 78) return "[SYNCED FUTURE]";
        else if (phraseId == 79) return "[OPEN RHYTHM]";
        else if (phraseId == 80) return "[SHARED DREAM]";
        else if (phraseId == 81) return "[TECH SPIRIT]";
        else if (phraseId == 82) return "[CHAIN SPIRIT]";
        else if (phraseId == 83) return "[OPEN MAPS]";
        else if (phraseId == 84) return "[FREE FLOW]";
        else if (phraseId == 85) return "[PEOPLE ENGINE]";
        else if (phraseId == 86) return "[NATIVE ONCHAIN]";
        else if (phraseId == 87) return "[NETWORK SOUL]";
        else if (phraseId == 88) return "[SHARED GOAL]";
        else if (phraseId == 89) return "[WARM DIGITAL]";
        else if (phraseId == 90) return "[SHARED SPARK]";
        else if (phraseId == 91) return "[UNIFIED BUILD]";
        else if (phraseId == 92) return "[VERIFIED LIFE]";
        else if (phraseId == 93) return "[REAL TIME]";
        else if (phraseId == 94) return "[FREE CONNECT]";
        else if (phraseId == 95) return "[OWN IT ALL]";
        else if (phraseId == 96) return "[CULTURE GROWS]";
        else if (phraseId == 97) return "[ONCHAIN MOVES]";
        else if (phraseId == 98) return "[DIGITAL NOW]";
        else if (phraseId == 99) return "[SHARED WORLD]";
        else if (phraseId == 100) return "[TRUST RAILS]";
        else if (phraseId == 101) return "[CREATE PULSE]";
        else if (phraseId == 102) return "[PEOPLE-DRIVEN]";
        else if (phraseId == 103) return "[CLEAR VALUE]";
        else if (phraseId == 104) return "[FREE MONEY]";
        else if (phraseId == 105) return "[SHAPED FUTURE]";
        else if (phraseId == 106) return "[CODE-POWERED]";
        else if (phraseId == 107) return "[NETWORK BORN]";
        else if (phraseId == 108) return "[TRUE OPENNESS]";
        else if (phraseId == 109) return "[ALL WELCOME]";
        else if (phraseId == 110) return "[PUBLIC SPACE]";
        else if (phraseId == 111) return "[ALL TRIBES]";
        else if (phraseId == 112) return "[TECH FRONTIER]";
        else if (phraseId == 113) return "[SHARED CODE]";
        else if (phraseId == 114) return "[GLOBAL TRIBE]";
        else if (phraseId == 115) return "[LINKED MINDS]";
        else if (phraseId == 116) return "[CHAIN BREATH]";
        else if (phraseId == 117) return "[WORLD SYNCING]";
        else if (phraseId == 118) return "[TRUST FLOW]";
        else if (phraseId == 119) return "[DIGITAL KIN]";
        else if (phraseId == 120) return "[FLUID SELF]";
        else if (phraseId == 121) return "[CHAIN-BORN]";
        else if (phraseId == 122) return "[FREE LIFE]";
        else if (phraseId == 123) return "[BORN DIGITAL]";
        else if (phraseId == 124) return "[SHARED STATE]";
        else if (phraseId == 125) return "[OPEN RHYTHM]";
        else if (phraseId == 126) return "[REAL DIGITAL]";
        else if (phraseId == 127) return "[SYSTEM RISING]";
        else if (phraseId == 128) return "[PURE ECONOMY]";
        else if (phraseId == 129) return "[VALUE FREED]";
        else if (phraseId == 130) return "[CREATOR REALM]";
        else if (phraseId == 131) return "[TECH COMMONS]";
        else if (phraseId == 132) return "[CHAIN ART]";
        else if (phraseId == 133) return "[NETWORK ALIVE]";
        else if (phraseId == 134) return "[SYNCED MINDS]";
        else if (phraseId == 135) return "[SHARED CANVAS]";
        else if (phraseId == 136) return "[SHARED ORBIT]";
        else if (phraseId == 137) return "[DIGITAL UNITY]";
        else if (phraseId == 138) return "[OPEN PROTOCOL]";
        else if (phraseId == 139) return "[CODE CULTURE]";
        else if (phraseId == 140) return "[OPEN BEAT]";
        else if (phraseId == 141) return "[CHAIN CLUSTER]";
        else if (phraseId == 142) return "[PEOPLE ROOTS]";
        else if (phraseId == 143) return "[FUTURE-CODED]";
        else if (phraseId == 144) return "[NET CULTURE]";
        else if (phraseId == 145) return "[CHAIN UNITED]";
        else if (phraseId == 146) return "[SHARED PATHS]";
        else if (phraseId == 147) return "[DIGITAL SYNC]";
        else if (phraseId == 148) return "[BUILT UNITED]";
        else if (phraseId == 149) return "[OPEN CREATION]";
        else if (phraseId == 150) return "[NETWORK RISE]";
        else if (phraseId == 151) return "[OPEN CIRCUITS]";
        else if (phraseId == 152) return "[OPEN COMMONS]";
        else if (phraseId == 153) return "[CHAIN BOND]";
        else if (phraseId == 154) return "[SHARED RISE]";
        else if (phraseId == 155) return "[FLUID NETS]";
        else if (phraseId == 156) return "[ONCHAIN UNITY]";
        else if (phraseId == 157) return "[MOTION NATIVE]";
        else if (phraseId == 158) return "[ENDLESS STATE]";
        else if (phraseId == 159) return "[SHARED FUTURE]";
        else if (phraseId == 160) return "[OPEN IDENTITY]";
        else if (phraseId == 161) return "[NATIVE VIBE]";
        else if (phraseId == 162) return "[NET BREATH]";
        else if (phraseId == 163) return "[LIVE PROTOCOL]";
        else if (phraseId == 164) return "[GLOBAL MESH]";
        else if (phraseId == 165) return "[FREE SYNC]";
        else if (phraseId == 166) return "[CHAIN ALIVE]";
        else if (phraseId == 167) return "[DIGITAL UNION]";
        else if (phraseId == 168) return "[CULTURE PULSE]";
        else if (phraseId == 169) return "[ENDLESS REACH]";
        else if (phraseId == 170) return "[SHARED RHYTHM]";
        else if (phraseId == 171) return "[CODE TRIBES]";
        else if (phraseId == 172) return "[FREE MOVEMENT]";
        else if (phraseId == 173) return "[CHAIN HARMONY]";
        else if (phraseId == 174) return "[UNITED MOVE]";
        else if (phraseId == 175) return "[TRUST WEB]";
        else if (phraseId == 176) return "[DIGITAL LIGHT]";
        else if (phraseId == 177) return "[CHAIN CLARITY]";
        else if (phraseId == 178) return "[CREATIVE MESH]";
        else if (phraseId == 179) return "[MICRO ECONOMY]";
        else if (phraseId == 180) return "[BUILDERS ONE]";
        else if (phraseId == 181) return "[VALUE SIGNAL]";
        else if (phraseId == 182) return "[DEEP CULTURE]";
        else if (phraseId == 183) return "[CULTURE MESH]";
        else if (phraseId == 184) return "[CODE PEOPLE]";
        else if (phraseId == 185) return "[SHARED SOUL]";
        else if (phraseId == 186) return "[OPEN REALM]";
        else if (phraseId == 187) return "[ONCHAIN KIN]";
        else if (phraseId == 188) return "[BRIGHT NET]";
        else if (phraseId == 189) return "[ALIGNED MINDS]";
        else if (phraseId == 190) return "[ENDLESS VALUE]";
        else if (phraseId == 191) return "[PROTOCOL HOME]";
        else if (phraseId == 192) return "[SYNC TOGETHER]";
        else if (phraseId == 193) return "[ALWAYS BUILD]";
        else if (phraseId == 194) return "[NETWORK GLOW]";
        else if (phraseId == 195) return "[CREATIVE WAVE]";
        else if (phraseId == 196) return "[CHAIN WARMTH]";
        else if (phraseId == 197) return "[OPEN LAYERS]";
        else if (phraseId == 198) return "[VALUE CIRCLES]";
        else if (phraseId == 199) return "[DIGITAL ORBIT]";
        else if (phraseId == 200) return "[CODE KINSHIP]";
        else if (phraseId == 201) return "[GLOBAL SYNC]";
        else if (phraseId == 202) return "[LIVING MESH]";
        else if (phraseId == 203) return "[HEARTCHAIN]";
        else if (phraseId == 204) return "[DIGITAL ETHER]";
        else if (phraseId == 205) return "[CHAIN MATTER]";
        else if (phraseId == 206) return "[TRUST FABRIC]";
        else if (phraseId == 207) return "[CULTURE WEB]";
        else if (phraseId == 208) return "[SHARED AIR]";
        else if (phraseId == 209) return "[NO BORDERS]";
        else if (phraseId == 210) return "[WORLDCHAIN]";
        else if (phraseId == 211) return "[OPEN HORIZON]";
        else if (phraseId == 212) return "[DIGITAL EDGE]";
        else if (phraseId == 213) return "[VALUE CLOUD]";
        else if (phraseId == 214) return "[CHAIN SPARK]";
        else if (phraseId == 215) return "[FLOW STATE]";
        else if (phraseId == 216) return "[PEOPLE POWER]";
        else if (phraseId == 217) return "[NETWORK HEART]";
        else if (phraseId == 218) return "[SHARED CODE]";
        else if (phraseId == 219) return "[HUMAN LEDGER]";
        else if (phraseId == 220) return "[VALUE BREATH]";
        else if (phraseId == 221) return "[NATIVE PULSE]";
        else if (phraseId == 222) return "[DIGITAL HUM]";
        else if (phraseId == 223) return "[CULTURE MAP]";
        else if (phraseId == 224) return "[LAYERED UNITY]";
        else if (phraseId == 225) return "[NETWORK BLOOM]";
        else if (phraseId == 226) return "[SHARED ORIGIN]";
        else if (phraseId == 227) return "[CHAIN STREAM]";
        else if (phraseId == 228) return "[ONCHAIN ORBIT]";
        else if (phraseId == 229) return "[CULTURE WAVE]";
        else if (phraseId == 230) return "[INFINITE NODE]";
        else if (phraseId == 231) return "[GLOBAL RELAY]";
        else if (phraseId == 232) return "[CREATE SIGNAL]";
        else if (phraseId == 233) return "[DIGITAL DRIFT]";
        else if (phraseId == 234) return "[CHAIN CANVAS]";
        else if (phraseId == 235) return "[ONCHAIN SPARK]";
        else if (phraseId == 236) return "[MESH CULTURE]";
        else if (phraseId == 237) return "[REAL SIGNAL]";
        else if (phraseId == 238) return "[CULTURE CHAIN]";
        else if (phraseId == 239) return "[CLOUD TRIBE]";
        else if (phraseId == 240) return "[CULTURE POINT]";
        else if (phraseId == 241) return "[NETWORK SOIL]";
        else if (phraseId == 242) return "[DIGITAL SEED]";
        else if (phraseId == 243) return "[ALL LINKED]";
        else if (phraseId == 244) return "[VALUE WEB]";
        else if (phraseId == 245) return "[SHARED CODE]";
        else if (phraseId == 246) return "[PEOPLE MESH]";
        else if (phraseId == 247) return "[OPEN PULSE]";
        else if (phraseId == 248) return "[CHAIN DWELL]";
        else if (phraseId == 249) return "[WOVEN VALUE]";
        else if (phraseId == 250) return "[DIGITAL NEST]";
        else if (phraseId == 251) return "[GLOBAL WEAVE]";
        else if (phraseId == 252) return "[OPEN WEAVE]";
        else if (phraseId == 253) return "[WORLD MESH]";
        else if (phraseId == 254) return "[SHARED LINK]";
        else if (phraseId == 255) return "[TRUST MESH]";
        else if (phraseId == 256) return "[CHAIN RIPPLE]";
        else if (phraseId == 257) return "[VALUE RIPPLE]";
        else if (phraseId == 258) return "[CREATIVE LINK]";
        else if (phraseId == 259) return "[NETWORK SOUL]";
        else if (phraseId == 260) return "[ONCHAIN DRIFT]";
        else if (phraseId == 261) return "[CULTURE SPARK]";
        else if (phraseId == 262) return "[CODE LIFE]";
        else if (phraseId == 263) return "[DIGITAL HOME]";
        else if (phraseId == 264) return "[CHAIN HABITAT]";
        else if (phraseId == 265) return "[MESH UNITY]";
        else if (phraseId == 266) return "[FLOW CULTURE]";
        else if (phraseId == 267) return "[TRUST LAYER]";
        else if (phraseId == 268) return "[ONCHAIN BLOOM]";
        else if (phraseId == 269) return "[VALUE FIELD]";
        else if (phraseId == 270) return "[DIGITAL QUIET]";
        else if (phraseId == 271) return "[CHAIN WHISPER]";
        else if (phraseId == 272) return "[OPEN WHISPER]";
        else if (phraseId == 273) return "[SOFT NETWORK]";
        else if (phraseId == 274) return "[ONCHAIN CALM]";
        else if (phraseId == 275) return "[LAYERED TRUST]";
        else if (phraseId == 276) return "[STORY CHAIN]";
        else if (phraseId == 277) return "[CHAIN STORIES]";
        else if (phraseId == 278) return "[DIGITAL TIDE]";
        else if (phraseId == 279) return "[SHARED TIDE]";
        else if (phraseId == 280) return "[HUMAN FIRST]";
        else if (phraseId == 281) return "[PEOPLE SYNC]";
        else if (phraseId == 282) return "[SHARED FLOW]";
        else if (phraseId == 283) return "[GLOBAL PULSE]";
        else if (phraseId == 284) return "[SHARED PULSE]";
        else if (phraseId == 285) return "[NETWORK ECHO]";
        else if (phraseId == 286) return "[CULTURE ECHO]";
        else if (phraseId == 287) return "[CHAIN ECHO]";
        else if (phraseId == 288) return "[SIGNAL RISE]";
        else if (phraseId == 289) return "[REAL CULTURE]";
        else if (phraseId == 290) return "[INFINITE FLOW]";
        else if (phraseId == 291) return "[OPEN PARTS]";
        else if (phraseId == 292) return "[CHAIN PARTS]";
        else if (phraseId == 293) return "[SYNC CULTURE]";
        else if (phraseId == 294) return "[DIGITAL WINDS]";
        else if (phraseId == 295) return "[CHAIN AIR]";
        else if (phraseId == 296) return "[UNIFIED TRUST]";
        else if (phraseId == 297) return "[CHAIN AS ONE]";
        else if (phraseId == 298) return "[CULTURE ALIVE]";
        else if (phraseId == 299) return "[ALL TOGETHER]";
        else return "]";
    }
}
